version: '3'
services:
  nginx:
   container_name: v-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 8082:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d

  elasticsearch:
    container_name: v-elastic
    image: blacktop/elasticsearch:6.7
    environment:
      cluster.name: "docker-cluster"
      transport.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      node.ingest: "false"
    restart: always
    ports:
    - 9201:9200
    - 9301:9300
  
  recommend:
    container_name: v-recommend
    build: ./recpro
    volumes:
      - ./recpro/source:/app
    depends_on:
      - mysql
  
  mysql:
    container_name: v-mysql
    image: mysql/mysql-server:5.7
    environment:
    # MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: always
    
  app:
    container_name: v-app
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
      - recommend
      - elasticsearch
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker